name: Run Robot Framework Selenium Test (Chrome)

on:
  workflow_dispatch:

jobs:
  robot-selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chrome and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Use bundled Chromedriver
      run: |
        sudo mv chromedriver.exe /usr/bin/chromedriver.exe
        sudo chmod +x /usr/bin/chromedriver.exe

    - name: Install Robot Framework and SeleniumLibrary
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Run Selenium Test with Chrome
      run: |
        xvfb-run --auto-servernum robot newtest.robot
